# Copyright 2016 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

runtime: python39
default_expiration: 5m

handlers:
# A static file used for clock sync in the demo app
- url: /time.txt
  static_files: time.txt
  upload: time.txt
  expiration: 0
  http_headers:
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Headers: "If-Modified-Since,Range,Origin"
    Access-Control-Expose-Headers: "Date"
    Access-Control-Max-Age: "2592000"

# These used to exist in the repo, but have been generated server-side for many
# years now.
- url: /assets/poster.jpg
  script: auto
- url: /assets/audioOnly.gif
  script: auto

# Serve favicon.ico from the demo folder.
- url: /favicon.ico
  secure: always
  static_files: demo/favicon.ico
  upload: demo/favicon.ico

# For these folders, serve their indexes.
- url: /docs/api/
  secure: always
  static_files: docs/api/index.html
  upload: docs/api/index.html
- url: /demo/
  secure: always
  static_files: demo/index.html
  upload: demo/index.html
- url: /demo/
  secure: always
  static_files: demo/index.html
  upload: demo/index.html

# Serve everything else directly.
- url: /(.+)
  secure: always
  static_files: \1
  upload: .+
