name: Feature request
description: Suggest an idea for this project
labels: ["type: enhancement"]
body:
  - type: checkboxes
    id: faq
    attributes:
      label: FAQ
      options:
        - label: I have read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      placeholder: Add any other context or screenshots about the feature request here.
    validations:
      required: false

  - type: dropdown
    id: pr
    attributes:
      label: Are you planning to send a PR to add it?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
